version: '3.8'

services:
  app:
    build: .
    container_name: simple-node-app
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    restart: always

  redis:
    image: redis:8
    container_name: redis-server
    ports:
      - "6379:6379"